export enum TipoProducaoAgricola {
  FERTILIZANTES = 'FERTILIZANTES',
  FERTILIZANTE = 'FERTILIZANTE',
  DEFENSIVOS = 'DEFENSIVOS',
  DEFENSIVO = 'DEFENSIVO',
  PESTICIDAS = 'PESTICIDAS',
  SEMENTES = 'SEMENTES',
  SEMENTE = 'SEMENTE',
  COMBUSTIVEIS = 'COMBUSTIVEIS',
  COMBUSTIVEL = 'COMBUSTIVEL',
  ENERGIA = 'ENERGIA',
  MAQUINARIO = 'MAQUINARIO',
  OUTRO = 'OUTRO'
}

export enum ClasseProducaoAgricola {
  NITROGENADOS = 'NITROGENADOS',
  FOSFATADOS = 'FOSFATADOS',
  POTASSICOS = 'POTASSICOS',
  CALCARIOS = 'CALCARIOS',
  ORGANICOS = 'ORGANICOS',
  MICRONUTRIENTES = 'MICRONUTRIENTES',
  HERBICIDAS = 'HERBICIDAS',
  INSETICIDAS = 'INSETICIDAS',
  FUNGICIDAS = 'FUNGICIDAS',
  ACARICIDAS = 'ACARICIDAS',
  CEREAIS = 'CEREAIS',
  LEGUMINOSAS = 'LEGUMINOSAS',
  OLEAGINOSAS = 'OLEAGINOSAS',
  FORRAGEIRAS = 'FORRAGEIRAS',
  DIESEL = 'DIESEL',
  GASOLINA = 'GASOLINA',
  ETANOL = 'ETANOL',
  ELETRICA = 'ELETRICA',
  SOLAR = 'SOLAR',
  EOLICA = 'EOLICA',
  OUTRO = 'OUTRO'
}

export enum UnidadeProduto {
  KG = 'KG',
  T = 'T',
  G = 'G',
  L = 'L',
  ML = 'ML',
  KWH = 'KWH',
  MJ = 'MJ',
  HA = 'HA',
  M2 = 'M2',
  UNIDADE = 'UNIDADE',
  TONELADA = 'TONELADA',
  TON = 'TON',
  LITRO = 'LITRO',
  M3 = 'M3',
  HECTARE = 'HECTARE'
}

export enum FazParteDieta {
  SIM = 'SIM',
  NAO = 'NAO'
}

export enum FatoresEmissao {
  CALCULADO = 'CALCULADO',
  ESTIMADO = 'ESTIMADO'
}

export enum ModuloInsumo {
  PRODUCAO_AGRICOLA = 'PRODUCAO_AGRICOLA',
  REBANHO = 'REBANHO'
}

export enum EscopoEnum {
  ESCOPO1 = 'ESCOPO1',
  ESCOPO2 = 'ESCOPO2',
  ESCOPO3 = 'ESCOPO3',
  ESCOPO3_PRODUCAO = 'ESCOPO3_PRODUCAO',
  ESCOPO3_TRANSPORTE = 'ESCOPO3_TRANSPORTE'
}